version: "3.1"

services:
  app:
    image: docker/englishtown
    restart: unless-stopped
    ports:
      - "3000:3000"
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_PASSWORD
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: data_username
      MONGO_INITDB_ROOT_PASSWORD: node-template
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: techbase-test
